<a href="https://colab.research.google.com/github/AnitaTasnim/image_processing/blob/main/normalize_image_channel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

here we will see :  computing the mean and standard deviation per channel

 Let's work with your example of images with a shape of 3x12x12 and a total of 34 images in the dataset.


 here's an example of a dataset with 34 images, each having a shape of 3x12x12, represented as tensors:

In [1]:
import torch
import random


In [3]:
sample_tensor  =  torch.rand(3,12,12)
sample_tensor

tensor([[[0.6817, 0.5277, 0.7583, 0.2656, 0.5929, 0.2914, 0.3801, 0.5659,
          0.9257, 0.6986, 0.0244, 0.6465],
         [0.6289, 0.5180, 0.2573, 0.9665, 0.6742, 0.5261, 0.9814, 0.2737,
          0.7311, 0.1777, 0.6173, 0.4752],
         [0.2755, 0.5504, 0.3851, 0.4635, 0.5547, 0.9153, 0.0340, 0.8401,
          0.0443, 0.3834, 0.9163, 0.2286],
         [0.8799, 0.8325, 0.9499, 0.2749, 0.1604, 0.7866, 0.6121, 0.7358,
          0.0780, 0.5159, 0.4526, 0.2086],
         [0.9666, 0.1806, 0.6083, 0.5074, 0.5861, 0.3373, 0.3374, 0.3094,
          0.0855, 0.1873, 0.9475, 0.3992],
         [0.2288, 0.7631, 0.6179, 0.4684, 0.6750, 0.7380, 0.7717, 0.9357,
          0.6757, 0.6093, 0.1249, 0.2717],
         [0.3284, 0.0040, 0.4349, 0.0737, 0.9141, 0.9444, 0.1704, 0.6208,
          0.0089, 0.2498, 0.1210, 0.7926],
         [0.3650, 0.7577, 0.3147, 0.2449, 0.1262, 0.8938, 0.0223, 0.1059,
          0.0842, 0.6543, 0.8635, 0.5028],
         [0.9188, 0.8360, 0.3063, 0.0651, 0.0557, 0.0697, 0.9105

In [4]:
#create a list to store image tensors
image_tensors = []


#generate 34 random images for the dataset
for _ in range(34):
  img = torch.rand(3,12,12)
  image_tensors.append(img)



In [7]:
len(image_tensors)

34

In [8]:
example_stack = torch.stack(image_tensors)
example_stack

tensor([[[[2.2186e-01, 1.4804e-01, 5.1479e-01,  ..., 4.4383e-01,
           2.5164e-01, 8.0758e-01],
          [8.2834e-01, 6.1846e-01, 6.4392e-01,  ..., 1.7838e-01,
           8.2920e-01, 5.2979e-01],
          [1.9355e-01, 9.2486e-01, 1.0212e-01,  ..., 4.1709e-01,
           8.1611e-01, 1.9077e-01],
          ...,
          [6.7714e-01, 5.8313e-01, 7.1825e-01,  ..., 2.1262e-02,
           7.5509e-01, 3.2688e-01],
          [1.1924e-01, 1.6249e-01, 4.8864e-04,  ..., 5.9504e-01,
           9.6764e-01, 7.7533e-01],
          [6.2839e-01, 4.9183e-01, 2.2252e-03,  ..., 6.9962e-01,
           5.4270e-01, 8.2424e-01]],

         [[6.3660e-01, 5.0426e-01, 8.8666e-01,  ..., 5.3990e-01,
           6.1234e-01, 1.2510e-01],
          [7.0309e-01, 2.5630e-06, 8.4639e-02,  ..., 5.0931e-01,
           2.2954e-01, 7.6940e-01],
          [8.5965e-01, 8.8955e-01, 5.2009e-01,  ..., 8.9319e-02,
           9.9443e-02, 8.8232e-02],
          ...,
          [1.5632e-01, 7.3871e-01, 8.3197e-01,  ..., 2.4719

In [9]:
example_stack.shape


torch.Size([34, 3, 12, 12])

In [10]:
## Stack the image tensors into a single tensor
dataset_tensor = torch.stack(image_tensors, dim=0)

dataset_tensor

tensor([[[[2.2186e-01, 1.4804e-01, 5.1479e-01,  ..., 4.4383e-01,
           2.5164e-01, 8.0758e-01],
          [8.2834e-01, 6.1846e-01, 6.4392e-01,  ..., 1.7838e-01,
           8.2920e-01, 5.2979e-01],
          [1.9355e-01, 9.2486e-01, 1.0212e-01,  ..., 4.1709e-01,
           8.1611e-01, 1.9077e-01],
          ...,
          [6.7714e-01, 5.8313e-01, 7.1825e-01,  ..., 2.1262e-02,
           7.5509e-01, 3.2688e-01],
          [1.1924e-01, 1.6249e-01, 4.8864e-04,  ..., 5.9504e-01,
           9.6764e-01, 7.7533e-01],
          [6.2839e-01, 4.9183e-01, 2.2252e-03,  ..., 6.9962e-01,
           5.4270e-01, 8.2424e-01]],

         [[6.3660e-01, 5.0426e-01, 8.8666e-01,  ..., 5.3990e-01,
           6.1234e-01, 1.2510e-01],
          [7.0309e-01, 2.5630e-06, 8.4639e-02,  ..., 5.0931e-01,
           2.2954e-01, 7.6940e-01],
          [8.5965e-01, 8.8955e-01, 5.2009e-01,  ..., 8.9319e-02,
           9.9443e-02, 8.8232e-02],
          ...,
          [1.5632e-01, 7.3871e-01, 8.3197e-01,  ..., 2.4719

In [11]:
dataset_tensor.shape

torch.Size([34, 3, 12, 12])

In [12]:
#
#If you use dim=3 when stacking the image tensors, it will stack the tensors along the 3rd dimension. Here's how it would work:
dataset_tensor = torch.stack(image_tensors, dim=3)

dataset_tensor

tensor([[[[2.2186e-01, 4.5409e-01, 3.7609e-01,  ..., 9.0323e-01,
           3.4680e-02, 9.2879e-01],
          [1.4804e-01, 8.9003e-01, 6.6240e-01,  ..., 4.5764e-01,
           3.4770e-01, 8.1077e-01],
          [5.1479e-01, 1.7021e-01, 5.0592e-01,  ..., 3.1701e-01,
           1.4120e-01, 4.9195e-01],
          ...,
          [4.4383e-01, 1.8417e-01, 7.9678e-01,  ..., 1.6629e-01,
           6.8507e-01, 8.1939e-01],
          [2.5164e-01, 2.6579e-01, 6.0033e-01,  ..., 6.2129e-01,
           7.0939e-01, 9.4583e-01],
          [8.0758e-01, 9.8605e-01, 3.2296e-01,  ..., 6.7856e-01,
           1.9210e-01, 9.7734e-01]],

         [[8.2834e-01, 2.4105e-01, 1.8680e-01,  ..., 5.0592e-01,
           9.4547e-01, 3.9429e-02],
          [6.1846e-01, 2.2424e-01, 2.6825e-01,  ..., 4.6627e-01,
           6.3545e-01, 3.1400e-01],
          [6.4392e-01, 9.0503e-01, 2.3360e-01,  ..., 1.4753e-01,
           1.9555e-01, 9.9187e-01],
          ...,
          [1.7838e-01, 1.0885e-01, 5.7579e-01,  ..., 7.7408

#how .view() works?


The .view method in PyTorch is used to reshape a tensor. It allows you to change the dimensions of a tensor while keeping the total number of elements the same.

In [13]:
#create a 1D tensor with 12 elements
tensor1d = torch.arange(12)
tensor1d

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
#reshape it into 2D tensor with 3  rows and 5 cols
tensor2d  = tensor1d.view(3,4)
tensor2d

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [17]:
tensor3d = tensor1d.view(2,2,3)
tensor3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [18]:
tensor3d = tensor2d.view(2,2,3)
tensor3d

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

In [38]:
tensor_new  =  tensor3d.view(2,-1) # -1 kno use kori??
#2,6 dile valid hoto, -1 dile o auto j number ta jay seta dhore ney.
#
tensor_new

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

create  a  3D tensor

In [19]:
# Create a 4D tensor
tensor_4d = torch.Tensor(3, 6, 6,5) #C,H,W  5-images # no it cant generate
tensor_4d

tensor([[[[ 1.1210e-44,  0.0000e+00,  0.0000e+00,  2.8026e-45,  5.6052e-45],
          [ 7.2128e+22,  7.5551e+31,  2.0535e-19,  4.7630e+30,  1.8395e+25],
          [ 6.6652e-33,  1.0647e+24,  1.2102e+25,  1.7841e+25,  3.1025e+27],
          [ 8.7506e-04,  1.3889e-16,  7.0072e+22,  4.5164e+16,  7.9033e+08],
          [ 3.4291e+30,  1.6121e-19,  5.0714e+36,  1.8752e-19,  9.1201e-12],
          [ 2.0336e-01,  1.0772e+18,  2.8183e+20,  7.0067e+22,  4.2850e+28]],

         [[ 1.8037e+28,  1.1092e+27,  7.3387e+28,  8.9746e-33,  1.4322e-16],
          [ 7.0072e+22,  4.5164e+16,  7.9033e+08,  3.4291e+30,  1.6121e-19],
          [ 5.0714e+36,  1.8752e-19,  9.1201e-12,  2.0336e-01,  1.0772e+18],
          [ 7.2716e+31,  4.1217e+21,  1.1045e-32,  7.0292e+28,  1.1723e-19],
          [ 1.7664e+22,  3.9604e-11,  1.6021e+25,  4.7341e+22,  2.8826e+32],
          [ 1.8524e+28,  1.9519e-19,  6.7541e+34,  1.8523e+28,  2.8183e+20]],

         [[ 7.0067e+22,  4.9658e+28,  1.8589e+34,  1.8179e+31,  1.8524e+

#creating small images datset tensor

In [20]:
#create a list to store image tensors
images_tensors = []


#generate 5 random images for the dataset
for _ in range(5):
  imgs = torch.rand(3,6,6)
  images_tensors.append(imgs)


In [21]:
images_tensors

[tensor([[[0.7536, 0.1124, 0.5572, 0.3406, 0.4241, 0.9122],
          [0.4719, 0.8793, 0.9147, 0.5907, 0.6400, 0.4010],
          [0.9130, 0.7038, 0.7152, 0.7855, 0.5518, 0.4229],
          [0.1960, 0.8099, 0.6489, 0.4498, 0.7360, 0.4607],
          [0.9963, 0.0837, 0.3300, 0.4604, 0.1415, 0.4275],
          [0.5344, 0.0967, 0.3448, 0.0300, 0.2206, 0.2921]],
 
         [[0.2663, 0.8442, 0.5909, 0.6503, 0.8951, 0.8027],
          [0.9733, 0.4795, 0.8565, 0.1623, 0.1438, 0.7105],
          [0.9834, 0.2851, 0.8261, 0.8696, 0.0202, 0.4897],
          [0.0191, 0.0588, 0.5845, 0.3412, 0.3097, 0.1493],
          [0.4409, 0.3178, 0.4489, 0.0842, 0.8135, 0.5939],
          [0.9697, 0.8627, 0.4451, 0.4850, 0.2626, 0.2271]],
 
         [[0.2567, 0.1195, 0.1859, 0.9758, 0.7279, 0.6709],
          [0.9493, 0.0171, 0.0480, 0.3468, 0.1251, 0.5819],
          [0.9597, 0.7795, 0.6547, 0.0023, 0.2071, 0.5633],
          [0.9447, 0.3899, 0.8283, 0.1711, 0.6067, 0.7183],
          [0.9736, 0.2875, 0.9708,

In [24]:
dataset_tensors = torch.stack(images_tensors, dim=0)
dataset_tensors  #it will stack the tensors along the 0th dimension  # evabe image wis evag korte parteci

tensor([[[[0.7536, 0.1124, 0.5572, 0.3406, 0.4241, 0.9122],
          [0.4719, 0.8793, 0.9147, 0.5907, 0.6400, 0.4010],
          [0.9130, 0.7038, 0.7152, 0.7855, 0.5518, 0.4229],
          [0.1960, 0.8099, 0.6489, 0.4498, 0.7360, 0.4607],
          [0.9963, 0.0837, 0.3300, 0.4604, 0.1415, 0.4275],
          [0.5344, 0.0967, 0.3448, 0.0300, 0.2206, 0.2921]],

         [[0.2663, 0.8442, 0.5909, 0.6503, 0.8951, 0.8027],
          [0.9733, 0.4795, 0.8565, 0.1623, 0.1438, 0.7105],
          [0.9834, 0.2851, 0.8261, 0.8696, 0.0202, 0.4897],
          [0.0191, 0.0588, 0.5845, 0.3412, 0.3097, 0.1493],
          [0.4409, 0.3178, 0.4489, 0.0842, 0.8135, 0.5939],
          [0.9697, 0.8627, 0.4451, 0.4850, 0.2626, 0.2271]],

         [[0.2567, 0.1195, 0.1859, 0.9758, 0.7279, 0.6709],
          [0.9493, 0.0171, 0.0480, 0.3468, 0.1251, 0.5819],
          [0.9597, 0.7795, 0.6547, 0.0023, 0.2071, 0.5633],
          [0.9447, 0.3899, 0.8283, 0.1711, 0.6067, 0.7183],
          [0.9736, 0.2875, 0.9708, 0

In [26]:
dataset_tensors = torch.stack(images_tensors, dim=3)
dataset_tensors  #it will stack the tensors along the 3rd dimension
# evabe full dataset k 3 ta channel a kore nici,  5 ta images R channel eksathe, G channel eksathe, B channel eksathe.

tensor([[[[0.7536, 0.8373, 0.0721, 0.7387, 0.3907],
          [0.1124, 0.4525, 0.1228, 0.7854, 0.6968],
          [0.5572, 0.8226, 0.9180, 0.7554, 0.8078],
          [0.3406, 0.2674, 0.9302, 0.7790, 0.3694],
          [0.4241, 0.1208, 0.8701, 0.0105, 0.5860],
          [0.9122, 0.8970, 0.2613, 0.4006, 0.7308]],

         [[0.4719, 0.9903, 0.9967, 0.8132, 0.7316],
          [0.8793, 0.6566, 0.0261, 0.8755, 0.7040],
          [0.9147, 0.3202, 0.8567, 0.0165, 0.0035],
          [0.5907, 0.1001, 0.3528, 0.0542, 0.6068],
          [0.6400, 0.3290, 0.6851, 0.0683, 0.5653],
          [0.4010, 0.2275, 0.7922, 0.9217, 0.0710]],

         [[0.9130, 0.6049, 0.4900, 0.7512, 0.4575],
          [0.7038, 0.6593, 0.0214, 0.7089, 0.3117],
          [0.7152, 0.3330, 0.3458, 0.4612, 0.1891],
          [0.7855, 0.4861, 0.8807, 0.7998, 0.6053],
          [0.5518, 0.5945, 0.3666, 0.3139, 0.0852],
          [0.4229, 0.9844, 0.0274, 0.7861, 0.3203]],

         [[0.1960, 0.3238, 0.2786, 0.4893, 0.1233],
      

In [27]:
dataset_tensors.shape

torch.Size([3, 6, 6, 5])

##view : It allows you to change the dimensions of a tensor while keeping the total number of elements the same.

In [28]:
dataset_tensors.shape

torch.Size([3, 6, 6, 5])

here I want to change its dimension, so that it keeps 3 channel and merges all the remaining dimensions into 1.



so 3*6*6 image will transformed into 3*36


and for 5 images it will be 3*180

In [39]:
dataset_new = dataset_tensors.view(3,-1)
dataset_new

tensor([[0.7536, 0.8373, 0.0721, 0.7387, 0.3907, 0.1124, 0.4525, 0.1228, 0.7854,
         0.6968, 0.5572, 0.8226, 0.9180, 0.7554, 0.8078, 0.3406, 0.2674, 0.9302,
         0.7790, 0.3694, 0.4241, 0.1208, 0.8701, 0.0105, 0.5860, 0.9122, 0.8970,
         0.2613, 0.4006, 0.7308, 0.4719, 0.9903, 0.9967, 0.8132, 0.7316, 0.8793,
         0.6566, 0.0261, 0.8755, 0.7040, 0.9147, 0.3202, 0.8567, 0.0165, 0.0035,
         0.5907, 0.1001, 0.3528, 0.0542, 0.6068, 0.6400, 0.3290, 0.6851, 0.0683,
         0.5653, 0.4010, 0.2275, 0.7922, 0.9217, 0.0710, 0.9130, 0.6049, 0.4900,
         0.7512, 0.4575, 0.7038, 0.6593, 0.0214, 0.7089, 0.3117, 0.7152, 0.3330,
         0.3458, 0.4612, 0.1891, 0.7855, 0.4861, 0.8807, 0.7998, 0.6053, 0.5518,
         0.5945, 0.3666, 0.3139, 0.0852, 0.4229, 0.9844, 0.0274, 0.7861, 0.3203,
         0.1960, 0.3238, 0.2786, 0.4893, 0.1233, 0.8099, 0.9014, 0.4520, 0.2759,
         0.8219, 0.6489, 0.2836, 0.2364, 0.1178, 0.1442, 0.4498, 0.7621, 0.6499,
         0.6477, 0.5169, 0.7

This reshapes the (3, 6, 6, 5) tensor into a 2D tensor with shape (3, 180), where each column represents a pixel value for a specific channel across all images and spatial dimensions.

#calculate mean per channel


To calculate the mean for each channel (R, G, and B), you need to collapse the spatial dimensions (height and width) while keeping the channel dimension intact. You can do this by reshaping the tensor and then calculating the mean. In code:

In [40]:
# Assuming you have a tensor 'imgs' with shape (3, 6, 6, 5)
channel_means = dataset_new.view(3, -1).mean(dim=1)

# 'channel_means' will be a tensor of shape (3,) where each element represents the mean value for one channel (R, G, B)


In [41]:
channel_means

tensor([0.4697, 0.4824, 0.5132])

#calculate standard deviation per channel

In [42]:
channel_stds = dataset_new.view(3, -1).std(dim=1)
channel_stds

tensor([0.2928, 0.2908, 0.3014])

#normalize

In [45]:
from torchvision import transforms

In [43]:
#With these numbers in our hands, we can initialize the Normalize transform

In [46]:
transforms.Normalize((0.4697, 0.4824, 0.5132),(0.2928, 0.2908, 0.3014))

Normalize(mean=(0.4697, 0.4824, 0.5132), std=(0.2928, 0.2908, 0.3014))